import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/header/Header";
import About from "../components/about/About";
import Skills from "../components/skills/Skills";
import Resume from "../components/resume/Resume";
import Portfolio from "../components/portfolio/Portfolio";
import Services from "../components/services/Services";
import Contact from "../components/Contact/Contact";
import Footer from "../components/footer.js/Footer";
import Hero from "../components/hero/Hero";
export default function Home() {
  const [isActive, setActive] = useState(false);
  console.log("🚀 ~ file: index.js ~ line 15 ~ Home ~ isActive", isActive);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isActive={isActive} setActive={setActive} />
      <Hero />
      <main id="main">
        <About />
        <Skills />
        <Resume />
        <Portfolio />
        {/* <Services /> */}
        <Contact />
      </main>
      <Footer />
    </div>
  );
}
